version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gomodguard
    - gosec
    - govet
    - ineffassign
    - noctx
    - nolintlint
    - staticcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (io.ReadCloser).Close
    gocritic:
      disabled-checks:
        # - dupImport
        # - whyNoLint
        # - appendAssign
        # - commentedOutCode
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gomodguard:
      blocked:
        modules:
          - github.com/golang/protobuf:
              recommendations:
                - google.golang.org/protobuf
              reason: see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules
          - github.com/pkg/errors:
              recommendations:
                - errors
                - github.com/mailgun/errors
              reason: Deprecated
    govet:
      disable:
        - fieldalignment
      enable-all: true
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 50
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
